import type { StructureDescriptor,StructureKind,StructureAssetConfig } from './types';
const d=(name:string,family:string,w=7,dep=6,h=3,floors=2,extra:Partial<StructureDescriptor>={}):StructureDescriptor=>({name,family,width:[3,w*2.5],depth:[3,dep*2.5],height:[2,h*3],floors,...extra});
export const STRUCTURE_DESCRIPTORS:Record<StructureKind,StructureDescriptor>={
 house:d('Casa simples','Moradias'),largeHouse:d('Casa grande','Moradias',10,8,6,3),cabin:d('Cabana','Moradias',5,5,3,1),abandonedHouse:d('Casa abandonada','Moradias',7,6,3,2,{ruin:.24}),ruinedHouse:d('Casa em ruínas','Moradias',7,6,3,2,{ruin:.65}),mansion:d('Mansão','Moradias',14,10,7,3),
 farm:d('Fazenda','Rurais',14,12),barn:d('Celeiro','Rurais',8,11,5,1),stable:d('Estábulo','Rurais',11,7,3,1),watchtower:d('Torre de vigia','Rurais',5,5,9,4),ruinedTower:d('Torre em ruínas','Rurais',5,5,9,4,{ruin:.62}),windmill:d('Moinho','Rurais',6,6,12,3),
 fortress:d('Fortaleza pequena','Fortificações',16,14,6,3),castle:d('Castelo','Fortificações',22,19,9,4),ruinedCastle:d('Castelo em ruínas','Fortificações',22,19,9,4,{ruin:.67}),ancientRuins:d('Ruínas antigas','Ancestrais',12,9,4,1,{ruin:.55}),temple:d('Templo antigo','Ancestrais',13,15,7,2),
 bridge:d('Ponte','Infraestrutura',12,4,3,1,{depth:[2,8]}),wall:d('Muralha','Infraestrutura',15,4,5,1,{depth:[1,8]}),gate:d('Portão','Infraestrutura',10,5,6,2),dock:d('Doca','Infraestrutura',12,8,3,1),lighthouse:d('Farol','Infraestrutura',6,6,13,4),
 camp:d('Acampamento','Conjuntos',12,10,3,1),village:d('Aldeia','Conjuntos',22,20,4,2),outpost:d('Posto avançado','Conjuntos',15,12,6,2),treehouse:d('Casa na árvore','Especiais',8,7,7,2),desert:d('Estrutura de deserto','Regionais',11,10,5,2,{biome:'gerudo'}),swamp:d('Estrutura de pântano','Regionais',9,8,4,1,{biome:'swamp'}),snowy:d('Estrutura nevada','Regionais',7,7,4,2,{biome:'hebra_snowy'}),mine:d('Mina','Especiais',10,10,5,1),underground:d('Estrutura subterrânea','Especiais',16,14,5,1),
};
STRUCTURE_DESCRIPTORS.camp.width[0]=10;STRUCTURE_DESCRIPTORS.camp.depth[0]=10;
// Functional minima keep towers, passages and room widths usable at the slider extremes.
for(const kind of ['fortress','castle','ruinedCastle'] as const){STRUCTURE_DESCRIPTORS[kind].width[0]=12;STRUCTURE_DESCRIPTORS[kind].depth[0]=10;}
for(const kind of ['farm','village','outpost','temple','treehouse','desert','swamp','mine','gate','lighthouse','underground'] as const){STRUCTURE_DESCRIPTORS[kind].width[0]=6;STRUCTURE_DESCRIPTORS[kind].depth[0]=6;}
export const STRUCTURE_PRESETS=Object.fromEntries(Object.entries(STRUCTURE_DESCRIPTORS).map(([key,p],i)=>{const type=key as StructureKind;const id=`structure_${type}` as const;return [id,{id,species:id,name:p.name,seed:7010+i,structure:{type,...(type==='stable'?{hayAmount:.7}:{}),biome:p.biome??'hyrule',scale:1,width:p.width[1]/2.5,depth:p.depth[1]/2.5,height:p.height[1]/3,floors:type==='largeHouse'||type==='mansion'||type==='castle'||type==='windmill'?2:1,complexity:.55,roof:'auto',roofPitch:.55,eaves:.55,asymmetry:.4,finish:.6,openingDensity:.6,annexes:true,balconies:true,ruin:p.ruin??0,vegetation:.3,snow:p.biome==='hebra_snowy'?.65:0,texelsPerMetre:32,palette:{wood:'#855b3e',stone:p.biome==='gerudo'?'#b19772':type==='windmill'?'#bbae91':(type==='temple'||type==='ancientRuins')?'#b4ae9b':type==='castle'||type==='ruinedCastle'?'#b1ad9d':'#929096',plaster:type==='desert'?'#e4c998':'#d3ded8',roof:p.biome==='gerudo'?'#b47f4c':type==='windmill'||(type==='outpost'||type==='treehouse')?'#3f6684':type==='barn'||type==='farm'?'#9c7044':type==='mansion'?'#426e58':type==='castle'||type==='ruinedCastle'?'#3f617b':'#42576a'},cutaway:true}} satisfies StructureAssetConfig];})) as Record<`structure_${StructureKind}`,StructureAssetConfig>;
