import type {StructurePlan,StructureStreams,V3} from './types';import {settleDebris} from './debris';
export function applyStructureDamage(source:StructurePlan,ruin:number,streams:StructureStreams):StructurePlan {const p=structuredClone(source);if(ruin<=0)return p;const all=[...p.walls,...p.roofs,...p.pieces];const removed=new Set<string>();const dependencies=new Map<string,typeof p.supports>();p.supports.forEach(s=>{const links=dependencies.get(s.component)??[];links.push(s);dependencies.set(s.component,links);});const lostSupport=(component:string)=>{const links=dependencies.get(component)??[];return links.length>0&&links.filter(s=>!removed.has(s.on)).length<(links[0].minimum??links.length);};
 const position=(o:any):V3=>o.position??(o.start?[(o.start[0]+o.end[0])/2,o.bottom+o.height/2,(o.start[2]+o.end[2])/2]:[o.x,o.y,o.z]);
 for(const obj of all){if('role' in obj&&['foundation','ancient-plinth','temple-platform'].includes(obj.role))continue;const pos=position(obj),rnd=streams.streamFor('damage',obj.id),field=(Math.sin(pos[0]*.45+source.seed*.17)+Math.cos(pos[2]*.45-source.seed*.11))*.12;const threshold=Math.max(.10,Math.min(.94,.48+field+(rnd()-.5)*.32));obj.damage=ruin;
 if(ruin>=threshold){obj.removed=true;removed.add(obj.id);}
 }
 let changed=true;while(changed){changed=false;for(const edge of p.supports)if(lostSupport(edge.component)&&!removed.has(edge.component)){removed.add(edge.component);const item=all.find(x=>x.id===edge.component);if(item)item.removed=true;changed=true;}}
 // Remaining roof must retain enough continuous wall/column support.
 for(const roof of p.roofs){const walls=p.walls.filter(w=>w.volume===roof.volume);const posts=p.pieces.filter(piece=>piece.kind==='beam'&&piece.role==='corner-post'&&!piece.removed&&piece.end&&Math.abs(piece.end[1]-roof.y)<.3&&Math.abs(piece.position[0]-roof.x)<=roof.width/2+.1&&Math.abs(piece.position[2]-roof.z)<=roof.depth/2+.1);if(walls.length&&walls.filter(w=>!w.removed).length<2||!walls.length&&posts.length<2&&roof.volume.startsWith('volume_')){roof.removed=true;removed.add(roof.id);}}
 changed=true;while(changed){changed=false;for(const edge of p.supports)if(lostSupport(edge.component)&&!removed.has(edge.component)){const item=all.find(x=>x.id===edge.component);if(item){item.removed=true;removed.add(item.id);changed=true;}}}
 for(const piece of p.pieces){if(piece.role==='observation'&&p.pieces.filter(x=>x.role==='tower-post'&&!x.removed).length<2){piece.removed=true;removed.add(piece.id);}}
 changed=true;while(changed){changed=false;for(const edge of p.supports)if(lostSupport(edge.component)&&!removed.has(edge.component)){const item=all.find(x=>x.id===edge.component);if(item){item.removed=true;removed.add(item.id);changed=true;}}}
 p.damage=[...removed].sort();p.openings=p.openings.filter(o=>{const w=p.walls.find(w=>w.id===o.wall);return w&&!w.removed&&o.bottom+o.height<=w.height;}).map(o=>({...o,broken:ruin>.18}));
 for(const wall of p.walls.filter(w=>w.removed&&w.bottom<.5)){const length=Math.hypot(wall.end[0]-wall.start[0],wall.end[2]-wall.start[2]),rnd=streams.streamFor('stump',wall.id);const h=.25+rnd()*.6;const size:V3=[length,h,wall.thickness];p.debris.push({id:'stump_'+wall.id,kind:'box',position:[(wall.start[0]+wall.end[0])/2,h/2,(wall.start[2]+wall.end[2])/2],size,rotation:[0,-Math.atan2(wall.end[2]-wall.start[2],wall.end[0]-wall.start[0]),0],material:wall.material,support:'ground',role:'wall-remnant'});}
 for(const id of removed){const obj=all.find(x=>x.id===id)!;const pos=position(obj),rnd=streams.streamFor('debris',id);const size:V3=[.25+rnd()*.45,.15+rnd()*.25,.22+rnd()*.38];p.debris.push({id:'debris_'+id,kind:('material' in obj&&obj.material==='wood')?'box':'rock',position:[pos[0]+(rnd()-.5)*2,size[1]/2,pos[2]+(rnd()-.5)*2],size,rotation:[0,rnd()*Math.PI,0],material:'material' in obj?obj.material:'stone',support:'ground',role:'debris'});}
 return settleDebris(p);}
