import './treeCanvasFixture';
import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';import {buildStructurePlan} from '../src/structures/plan';import {buildRoof} from '../src/structures/geometry/roofs';import {applyStructureDamage} from '../src/structures/damage';import {structureStreams} from '../src/structures/random';import {createStructure} from '../src/structures/generator';import {fixture} from './structureFixtures';import {structureCapabilities} from '../src/structures/capabilities';
test('wide and deep hip roofs meet every wall support contour',()=>{for(const [width,depth] of [[15,3],[3,15],[7,7]]){const p=buildStructurePlan(fixture('house',42,{roof:'hip',width,depth,annexes:false,balconies:false})),r=p.roofs[0],g=buildRoof(r),mesh=new THREE.Mesh(g,new THREE.MeshBasicMaterial({side:THREE.DoubleSide}));mesh.updateMatrixWorld();for(const [x,z] of [[r.x,r.z-r.depth/2],[r.x+r.width/2,r.z],[r.x,r.z+r.depth/2],[r.x-r.width/2,r.z]]){const ray=new THREE.Raycaster(new THREE.Vector3(x,50,z),new THREE.Vector3(0,-1,0)),hits=ray.intersectObject(mesh);assert.ok(hits.length);const underside=Math.min(...hits.map(h=>h.point.y));assert.ok(Math.abs(underside-r.y)<.01,JSON.stringify({width,depth,underside,wall:r.y}));}g.dispose();(mesh.material as THREE.Material).dispose();}});
test('raised platforms and barn trusses collapse when their structural supports are lost',()=>{for(const [type,seed,ruin] of [['swamp',42,.75],['barn',3,.6],['watchtower',42,.75],['dock',42,.75],['bridge',42,.75]] as const){const p=applyStructureDamage(buildStructurePlan(fixture(type,seed)),ruin,structureStreams(seed));for(const piece of p.pieces.filter(x=>['foundation','barn-truss','observation','dock-deck','deck'].includes(x.role)&&x.position[1]>1&&!x.removed)){const links=p.supports.filter(s=>s.component===piece.id);assert.ok(links.length&&links.every(s=>s.on!=='ground'),type+' '+piece.role+' is assigned ground');assert.ok(links.some(s=>!p.damage.includes(s.on)),type+' floats');}}});
test('flat and shed specialized roofs have matching framing and snow wall profiles',()=>{for(const type of ['barn','snowy'] as const)for(const roof of ['flat','shed'] as const){const p=buildStructurePlan(fixture(type,42,{roof})),r=p.roofs[0];for(const beam of p.pieces.filter(x=>x.role==='barn-truss'||x.role==='snow-brace'))assert.ok(Math.max(beam.position[1],beam.end![1])<=r.y+(r.kind==='flat'?0:r.rise)+.02,type+' frame protrudes');if(r.kind==='shed'){const front=p.walls.find(w=>w.id.endsWith('wall_0'))!;assert.ok(Math.abs(Math.abs(front.topRight!-front.topLeft!)-r.rise)<.001);}}});
test('fortified layouts have tower access and stairs reaching wall walks',()=>{for(const type of ['fortress','castle'] as const){const p=buildStructurePlan(fixture(type,42)),towers=p.volumes.filter(v=>v.role==='corner-tower');for(const v of towers){const walls=p.walls.filter(w=>w.volume===v.id);assert.ok(p.openings.some(o=>o.kind==='door'&&o.bottom===0&&walls.some(w=>w.id===o.wall)),type+' sealed tower');assert.ok(p.openings.some(o=>o.kind==='door'&&o.bottom>0&&walls.some(w=>w.id===o.wall)),type+' inaccessible wall walk');}assert.ok(p.accesses.some(a=>a.role==='stairs'&&a.to[1]>2));assert.ok(p.pieces.some(p=>p.role===(type==='fortress'?'fortress-wall-walk':'wall-walk')));if(type==='fortress')assert.equal(p.pieces.filter(p=>p.role==='fortress-tower').length,4);}});
test('shown controls correspond to grammar capabilities and water stays outside OBJ asset',()=>{for(const type of ['watchtower','lighthouse','farm','temple'] as const)assert.equal(structureCapabilities(type).floors,false,type);for(const type of ['bridge','dock','camp'] as const)assert.equal(structureCapabilities(type).windows,false,type);for(const type of ['watchtower','snowy','temple','ancientRuins'] as const)assert.equal(structureCapabilities(type).roof,false,type);for(const type of ['bridge','dock','swamp'] as const){const a=createStructure(fixture(type,42,{vegetation:0}));const water=a.group.getObjectByName('PresentationWater');assert.ok(water,type+' missing water');assert.equal(water!.userData.excludeFromOBJ,true);assert.equal(a.assetGroup.getObjectByName('PresentationWater'),undefined);a.dispose();}});

test('external stairs finish on a supported landing for wall and desert terraces',()=>{for(const type of ['wall','desert'] as const){const p=buildStructurePlan(fixture(type,42));for(const a of p.accesses.filter(a=>a.role==='stairs'&&a.to[1]>1)){assert.ok(p.pieces.some(piece=>piece.kind==='box'&&Math.abs(piece.position[1]+piece.size[1]/2-a.to[1])<.02&&Math.abs(piece.position[0]-a.to[0])<=piece.size[0]/2+.02&&Math.abs(piece.position[2]-a.to[2])<=piece.size[2]/2+.02),type+' stair ends in air');}}});
