import {Architect} from '../blueprint';import type {GrammarContext,V3} from '../types';
export function farm(c:GrammarContext){const a=new Architect(c),p=c.config,w=a.value(p.width),d=a.value(p.depth),roof=p.roof==='auto'?'thatch':p.roof;const home=a.building(-w*.26,d*.17,w*.35,d*.38,a.value(p.height),1,{roof});a.veranda(home);a.building(w*.26,d*.22,w*.26,d*.30,p.height*.85,1,{material:'wood',roof,role:'shed'});a.fence(0,0,w*1.02,d*1.02);const zone={id:'cultivation',x:0,z:-d*.22,width:w*.65,depth:d*.34,y:.02,kind:'cultivation' as const};a.plan.propZones.push(zone);for(let i=0;i<5;i++)a.piece('box',[-zone.width/2+(i+.5)*zone.width/5,.07,zone.z],[zone.width/8,.14,zone.depth],'earth','crop-row');return a.finish();}
export function barn(c:GrammarContext){
 const a=new Architect(c),p=c.config,w=a.value(p.width),d=a.value(p.depth),h=a.value(p.height),v=a.building(0,0,w,d,h,1,{material:'wood',roof:p.roof==='auto'?'thatch':p.roof,role:'barn'}),roof=a.plan.roofs[0];
 const door=a.plan.openings.find(o=>o.kind==='door')!;door.width=Math.min(w*.5,3.2);door.height=h*.72;
 const height=(x:number,z:number)=>roof.y+(roof.kind==='flat'?0:roof.kind==='shed'?roof.rise*((roof.shedDirection??1)*x/w+.5):roof.kind==='hip'?roof.rise*Math.min((w/2-Math.abs(x))/Math.min(w/2,d/2),(d/2-Math.abs(z))/Math.min(w/2,d/2)):roof.rise*(x<=-w/2+w*(roof.ridgeRatio??.5)?(x+w/2)/(w*(roof.ridgeRatio??.5)):(w/2-x)/(w*(1-(roof.ridgeRatio??.5)))));
 const foundation=a.plan.pieces.find(x=>x.role==='foundation')!.id;
 for(let i=0;i<4;i++){const z=-d/2+(i+.5)*d/4,left=height(-w/2,z),right=height(w/2,z),peakX=roof.kind==='shed'?(roof.shedDirection??1)*w/2:-w/2+w*(roof.ridgeRatio??.5),peak=height(peakX,z);const posts=[a.beam([-w/2,v.bottom,z],[-w/2,left,z],.18,'wood','barn-truss-post',foundation),a.beam([w/2,v.bottom,z],[w/2,right,z],.18,'wood','barn-truss-post',foundation)];
 const parts=roof.kind==='flat'||roof.kind==='shed'?[a.beam([-w/2,left,z],[w/2,right,z],.2,'wood','barn-truss',posts[0])]:[a.beam([-w/2,left,z],[peakX,peak,z],.2,'wood','barn-truss',posts[0]),a.beam([peakX,peak,z],[w/2,right,z],.2,'wood','barn-truss',posts[0]),a.beam([-w/2,roof.y,z],[w/2,roof.y,z],.17,'wood','barn-truss',posts[0])];parts.forEach(id=>a.depend(id,posts,2));
 }return a.finish();}
export function stable(c:GrammarContext){const a=new Architect(c),p=c.config,w=a.value(p.width),d=a.value(p.depth),h=a.value(p.height);a.building(0,0,w,d,h,1,{open:true,roof:p.roof==='auto'?'gable':p.roof});const n=3+Math.floor(a.rnd()*3),bay=w/n;for(let i=0;i<=n;i++){const x=-w/2+i*bay;a.piece('box',[x,.8,d*.12],[.14,1.3,d*.55],'wood','stall');a.beam([x,0,-d/2],[x,h,-d/2],.18,'wood','stall-post');}a.piece('box',[0,1,d/2],[w,1.6,.15],'wood','stall-back');return a.finish();}
export function watchtower(c:GrammarContext){const a=new Architect(c),p=c.config,w=a.value(p.width),d=a.value(p.depth),h=a.value(p.height);const support=a.piece('box',[0,.12,0],[w*.85,.24,d*.85],'stone','foundation');for(const x of [-w*.34,w*.34])for(const z of [-d*.34,d*.34])a.beam([x,.2,z],[x,h,z],.27,'wood','tower-post',support);for(const z of [-d*.34,d*.34]){a.beam([-w*.34,.4,z],[w*.34,h*.75,z],.19,'wood','tower-brace',support);a.beam([w*.34,.4,z],[-w*.34,h*.75,z],.19,'wood','tower-brace',support);}const deck=a.piece('box',[0,h,0],[w,.2,d],'wood','observation',support);a.depend(deck,a.plan.pieces.filter(p=>p.role==='tower-post').map(p=>p.id),2);a.beam([-w/2,h+1,d/2],[w/2,h+1,d/2],.12,'wood','rail',deck);for(const side of [-1,1])a.beam([side*w/2,h+1,-d/2],[side*.65,h+1,-d/2],.12,'wood','rail',deck);for(const x of [-w/2,w/2]){a.beam([x,h,-d/2],[x,h+2,-d/2],.18,'wood','roof-post',deck);a.beam([x,h,d/2],[x,h+2,d/2],.18,'wood','roof-post',deck);}a.plan.roofs.push({id:'tower-roof',volume:'tower',x:0,z:0,width:w,depth:d,y:h+2,rise:w*.38,eaves:p.eaves,kind:'gable',material:'roof'});a.depend('tower-roof',a.plan.pieces.filter(p=>p.role==='roof-post').map(p=>p.id),2);const footZ=-d/2-1.6,topZ=-d/2-.08;const rails=[-1,1].map(side=>a.beam([side*.5,.10,footZ],[side*.5,h+.75,topZ+.1],.16,'wood','tower-ladder-rail',deck));const steps=Math.ceil(h/.30);for(let i=1;i<=steps;i++){const t=i/steps,y=.10+(h-.20)*t,z=footZ+(topZ+.1-footZ)*(y-.10)/(h+.65);const rung=a.beam([-.50,y,z],[.50,y,z],.12,'wood','tower-ladder-rung',rails[0]);a.depend(rung,rails,2);}a.plan.accesses.push({id:'tower-ladder-access',from:[0,.10,footZ],to:[0,h,topZ],width:1,role:'ladder'});return a.finish();}
export function ruinedTower(c:GrammarContext){return watchtower(c);}
export {windmill} from './windmill';
